import { EDGE1, EDGE2, onCrate1, onStack, stairs, fell } from '../w1-5-parts.js';

export default () => [
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 12 },
  { do: 'swap', to: 0 },
  { do: 'walk', p: 0, to: 10 },
  { do: 'walkJump', p: 0, to: 12, at: 11 },
  { do: 'jump', p: 0, dir: 1 },
  { do: 'walk', p: 0, to: 18, hop: true },
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 7 },
  { do: 'swap', to: 0 },
  { do: 'walk', p: 0, px: EDGE1 },
  fell(0, 1700),
  { do: 'walk', p: 0, to: 26 },
  { do: 'squish', p: 0, on: true },
  { do: 'swap', to: 1 },
  ...onCrate1(1, 22),
  { do: 'walk', p: 1, to: 23 },
  { do: 'walkJump', p: 1, to: 28, at: 25.2 },
  { do: 'walk', p: 1, to: 30.5, hop: true },
  { do: 'swap', to: 0 },
  { do: 'squish', p: 0, on: false },
  { do: 'walk', p: 0, to: 21 },
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, px: EDGE2 },
  fell(1, 1500),
  { do: 'walk', p: 1, to: 33.2, hop: true },
  { do: 'walk', p: 1, px: EDGE2 },
  fell(2, 1400),
  ...stairs(1, 26),
  { do: 'swap', to: 0 },
  ...onStack(0, 30),
  ...stairs(0, 28),
  { do: 'swap', to: 1 },
  { do: 'enter', p: 1 },
  { do: 'enter', p: 0 },
];
