import { PUSH_X, powered, liftReady, liftTop } from '../factory.js';

export default () => [
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 9 },
  { do: 'swap', to: 0 },
  { do: 'walk', p: 0, to: 7 },
  { do: 'walkJump', p: 0, to: 9, at: 8 },
  { do: 'jump', p: 0 },
  { do: 'walk', p: 0, px: PUSH_X },
  powered,
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 20, hop: true },
  { do: 'squish', p: 1, on: true },
  { do: 'swap', to: 0 },
  { do: 'walk', p: 0, to: 18, hop: true },
  { do: 'walkJump', p: 0, to: 20, at: 19 },
  { do: 'until', label: 'key', test: (s) => s.key.holder === 0 },
  { do: 'walk', p: 0, to: 22 },
  { do: 'swap', to: 1 },
  { do: 'squish', p: 1, on: false },
  { do: 'walk', p: 1, to: 21 },
  { do: 'swap', to: 0 },
  { do: 'follow', on: true },
  liftReady,
  { do: 'walk', p: 0, to: 24.8, tol: 20 },
  liftTop,
  { do: 'enter', p: 0 },
  { do: 'follow', on: false },
  { do: 'enter', p: 1 },
];
