export default () => [
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 10 },
  { do: 'until', label: 'shutter open', test: (s) => s.gates[0].open >= 1 },
  { do: 'swap', to: 0 },
  { do: 'walk', p: 0, to: 16, hop: true },
  { do: 'swap', to: 1 },
  { do: 'walk', p: 1, to: 18, hop: true },
  { do: 'walk', p: 1, to: 24.5, tol: 6 },
  { do: 'until', label: 'key', test: (s) => s.key.holder === 1 },
  { do: 'follow', on: true },
  { do: 'enter', p: 1 },
  { do: 'follow', on: false },
  { do: 'enter', p: 0 },
];
